exports.seed = function (knex, Promise) {
	return Promise.join(
		// Deletes ALL existing entries
		knex('posts').del(),

		// Inserts seed entries
		knex('posts').insert({
			user_id: 2,
			category: 4,
			timestamp: "01:30:00PM",
			dish_name: "Tasty Pasta",
			rest_name: "Tonys Restraunt",
			price: 20,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 1,
			category: 2,
			timestamp: "02:30:00PM",
			dish_name: "Stadium Hot Dogs with Jalapeno",
			rest_name: "Bobs Ballpark",
			price: 5,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: false,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 3,
			category: 1,
			timestamp: "03:30:00PM",
			dish_name: "Carne Asada Tacos",
			rest_name: "King Taco",
			price: 7,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 5,
			category: 3,
			timestamp: "04:30:00PM",
			dish_name: "Dim Sum",
			rest_name: "Thai Cuisine",
			price: 15,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 6,
			category: 2,
			timestamp: "05:30:00PM",
			dish_name: "Angus Beef Bacon Burger",
			rest_name: "Thai Cuisine",
			price: 10,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 2,
			category: 4,
			timestamp: "07:30:00PM",
			dish_name: "Tasty Pasta",
			rest_name: "Tonys Restraunt",
			price: 20,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 1,
			category: 2,
			timestamp: "06:30:00PM",
			dish_name: "Stadium Hot Dogs with Jalapeno",
			rest_name: "Bobs Ballpark",
			price: 5,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: false,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 3,
			category: 1,
			timestamp: "08:30:00PM",
			dish_name: "Carne Asada Tacos",
			rest_name: "King Taco",
			price: 7,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 5,
			category: 3,
			timestamp: "09:30:00PM",
			dish_name: "Dim Sum",
			rest_name: "Thai Cuisine",
			price: 15,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 6,
			category: 2,
			timestamp: "10:30:00PM",
			dish_name: "Angus Beef Bacon Burger",
			rest_name: "Thai Cuisine",
			price: 10,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 2,
			category: 4,
			timestamp: "11:30:00PM",
			dish_name: "Tasty Pasta",
			rest_name: "Tonys Restraunt",
			price: 20,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 1,
			category: 2,
			timestamp: "12:30:00PM",
			dish_name: "Stadium Hot Dogs with Jalapeno",
			rest_name: "Bobs Ballpark",
			price: 5,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: false,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 3,
			category: 1,
			timestamp: "01:30:00AM",
			dish_name: "Carne Asada Tacos",
			rest_name: "King Taco",
			price: 7,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 5,
			category: 3,
			timestamp: "02:30:00AM",
			dish_name: "Dim Sum",
			rest_name: "Thai Cuisine",
			price: 15,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		}),
		knex('posts').insert({
			user_id: 6,
			category: 2,
			timestamp: "03:30:00AM",
			dish_name: "Angus Beef Bacon Burger",
			rest_name: "Thai Cuisine",
			price: 10,
			picture_path: "/pathTo/img",
			veggie: false,
			gluten_free: true,
			spicy: false,
			rating: 5
		})		
	);
};